# Generated by Django 2.2.7 on 2021-03-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_createuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
